# Name of your application.
service: crm-frontend

# Name of the container image.
image: saptia14/crm-frontend-demo-portfolio-amaury

# Deploy to these servers.
servers:
  web:
    - 157.230.10.197

# Enable SSL auto certification via Let's Encrypt and routing via host header.
proxy:
  ssl: true
  host: crm-demo.soyamaury.dev
  app_port: 80

# Where you keep your container images.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Build arguments (passing the API URL to Vite at build time).
builder:
  arch: amd64
  args:
    VITE_API_HOST: https://api-demo.soyamaury.dev
